<?php

/**
 * BaseCustomer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $login
 * @property string $mail
 * @property string $name
 * @property string $password
 * 
 * @method string   getLogin()    Returns the current record's "login" value
 * @method string   getMail()     Returns the current record's "mail" value
 * @method string   getName()     Returns the current record's "name" value
 * @method string   getPassword() Returns the current record's "password" value
 * @method Customer setLogin()    Sets the current record's "login" value
 * @method Customer setMail()     Sets the current record's "mail" value
 * @method Customer setName()     Sets the current record's "name" value
 * @method Customer setPassword() Sets the current record's "password" value
 * 
 * @package    gym6
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customer');
        $this->hasColumn('login', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('mail', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}